# Generated by Django 3.2.7 on 2021-10-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='reviews',
            new_name='review',
        ),
    ]
