# Generated by Django 3.2.7 on 2021-09-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProjectsApp', '0001_initial'),
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='owner', to='userProjectsApp.project'),
        ),
    ]
