# Generated by Django 3.2.7 on 2021-09-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_rename_projects_profile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
